name: flutter_ui
description: A mix of Flutter UIs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_page_view_indicator: ^0.0.5
  google_fonts: ^2.1.1
  auth_buttons: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/profiles/
    - assets/images/auths/
    - assets/images/app/social_media_1/